config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.role == 'admin' } do
      mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  get '403', to: 'errors#forbidden', as: 'forbidden'
  get '404', to: 'errors#not_found', as: 'not_found'
  get '422', to: 'errors#unprocessable_entity'
  get '500', to: 'errors#internal_server_error'

  root to: "geo_refs#index"

  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'
  get 'profile/password', to: 'profile#password'
  patch 'profile/password', to: 'profile#update_password'

  resources :search, only: %i[index]
  resources :photos, only: %i[index show edit update destroy]
  resources :topos
  resources :zones, only: %i[index]
  resources :regulations, only: %i[index show edit update destroy] do
    resources :regulated_geo_refs, only: %i[new create]
  end
  resources :regulated_geo_refs, only: %i[edit update destroy]
  resources :inventories, only: [:show]
  resources :routes, only: %i[index show edit update destroy] do
    collection do
      get 'autocomplete'
    end
    resources :ascents, only: [:index, :new]
    resources :ticklists, only: [:index, :new]
    resources :photos, only: %i[index new create]
    resources :comments, only: %i[index new create]
    resources :inventories do
      member do
        put 'remove'
      end
    end
    resources :route_links, only: %i[new create edit update destroy]
    resources :versions, only: [:index]
  end
  resources :route_links, only: %i[show]

  resources :closures, only: %i[index show edit update destroy] do
    member do
      get :add_geo_ref_form
      post :add_geo_ref
      post :remove_geo_ref
      get :add_route_form
      post :add_route
      post :remove_route
    end
    collection do
      get :feed
    end
    resources :season_closures, only: %i[new create]
  end
  resources :season_closures, only: %i[edit update destroy]

  resources :ascents, only: %i[index show]
  resources :ticklists, only: %i[index show]

  resources :users, only: %i[show index] do
    resources :ascents, except: :show
    resources :ticklists, except: :show
    resources :photos, only: [:index]
    resources :versions, only: [:index]
  end

  resources :first_ascent_people do
    resources :versions, only: [:index]
    collection do
      get 'autocomplete'
    end
  end
  get 'scales/:scope', to: 'scales#table', defaults: { scope: 'climbing' }

  resources :geo_refs, except: :new  do
    collection do
      get(
        'new/:type',
        to: 'geo_refs#new',
        constraints: { type: /(Country|Region|Crag|Sector|Parking)/ },
        as: 'new'
      )
      get 'browse'
      get 'autocomplete'
      get 'map'
    end

    member do
      get 'map_items'
      get :sort_routes
      put :reorder_routes
      get :sort_childs
      put :reorder_childs
      get :select_items
      patch :move_items
    end

    resources :routes, only: %i[new create index] do
      collection do
        get :autocomplete
      end
    end
    resources :ascents, only: [:index]
    resources :ticklists, only: [:index]
    resources :approaches, only: [:index]
    resources :photos, only: %i[index new create]
    resources :topos
    resources :secondary_zones, only: %i[new create edit update destroy]
    resources :comments, only: %i[index new create]
    resources :paths, only: %i[index new create]
    resources :permissions, only: %i[index create edit update destroy]
    resources :regulations, only: %i[index new create]
    resources :closures, only: %i[index new create] do
      collection do
        get :new_with_template
        get :feed
      end
    end
    resources :versions, only: [:index]
  end

  resources :grades, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :styles, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :comments, only: %i[index edit update destroy]

  resources :paths, only: %i[index show edit update destroy] do
    member do
      post 'add_geo_ref'
      post 'remove_geo_ref'
      get 'map_items'
    end
  end

  resources :products, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :versions, only: [:index]

  get 'help', to: redirect('/help/README.html'), as: nil
  get 'help/*path', to: 'help#show', as: 'help'
  
  namespace :admin do
    root to: 'dashboard#dashboard'
    get '/monitoring', to: 'monitoring#index'
    get '/sys_info', to: 'sys_info#index'
    get '/background_jobs', to: 'background_jobs#index'
    resources :users do
      collection do
        get :members
        get :contributors
        get :admins
        get 'autocomplete'
      end
    end

    resources :vendors do
      collection do
        get 'autocomplete'
      end
    end
    resources :products do
      collection do
        get 'autocomplete'
      end
    end
  end

  get 'custom_layout', format: :css, to: 'custom_layout#index', as: :custom_layout

  get 'password_strength', to: 'password_strength#check'

  get '/abilities/:id', to: 'abilities#show'

  namespace :api do
    namespace :embed do
      namespace :v1 do
        resources :geo_refs, only: [] do
          collection do
            get :with_closures
          end
          resources :closures, only: %i[index] do
            collection do
              get :feed
            end
          end
        end
        resources :closures, only: %i[index] do
          collection do
            get :feed
          end
        end
      end
    end
  end

  health_check_routes
end

app/controllers/api/embed/v1/geo_refs_controller.rb
module Api
  module Embed
    module V1
      class GeoRefsController < Api::Embed::BaseController
        skip_authorization_check only: %i[with_closures]

        def with_closures
          @geo_refs = GeoRef.where(
            id: Closure.distinct.pluck(:geo_ref_id)
          ).accessible_by(current_ability, :read) \
            .page(params[:page])
          render json: GeoRefSerializer.new(
            @geo_refs,
            links: jsonapi_paginate_links(@geo_refs),
            meta: jsonapi_paginate_meta(@geo_refs),
          ).serializable_hash.to_json
        end
      end
    end
  end
end

app/controllers/geo_refs_controller.rb
class GeoRefsController < ApplicationController
  before_action(
    :set_geo_ref,
    only: %i[
      show edit update destroy
      map_items
      sort_routes reorder_routes
      sort_childs reorder_childs
      select_items move_items
    ]
  )
  before_action :set_move_items_params, only: %i[select_items move_items]
  skip_authorization_check only: %i[index browse autocomplete]
  back_navigatable_actions %i[index show browse]

  attr_accessor :geo_ref_for_paper_trail

  def autocomplete
    @geo_refs = GeoRef \
      .where('name ILIKE (?)', "%#{params[:term]}%") \
      .includes(:parent) \
      .accessible_by(current_ability, :read) \
      .order('LENGTH(geo_refs.name) ASC, geo_refs.name ASC') \
      .limit(10)
    render(
      json: @geo_refs.map do |g|
        parent = g.parent.present? ? "#{g.parent.name} / " : ''
        {
          id: g.id,
          value: g.name,
          label: "#{parent}#{g.name} (#{g.class.name})",
        }
      end
    )
  end

  def map
    # TODO select items based on map (geokit)
  end

  def map_items
    authorize! :read, @geo_ref
    @childs = @geo_ref.childs.with_location.accessible_by(current_ability, :read)

    @items = if @childs.any?
               @childs
             else
               [@geo_ref]
             end

    render json: GeoRef::MapItemSerializer.new(@items).serializable_hash.to_json
  end

  def browse
    @geo_refs = GeoRef.where(parent: nil).accessible_by(current_ability, :read)
    respond_to do |format|
      format.html 
    end
  end

  def index
    @q = GeoRef.ransack(params[:q])
    @geo_refs = @q.result \
      .accessible_by(current_ability, :read)\
      .order(created_at: :desc) \
      .page(params[:page])
    respond_to do |format|
      format.html 
    end
  end

  def show
    authorize! :read, @geo_ref
    @closures = @geo_ref.applicable_closures.includes(:relevant_season_closures)
    @route_closures = Closure.joins(:routes).where('routes.geo_ref_id': @geo_ref.id)
    @childs = childs
    @routes = routes.includes(:grade, closures: :relevant_season_closures)
    @topos = @geo_ref.topos.accessible_by(current_ability, :read)
  end

  def sort_childs
    authorize! :update, @geo_ref
    @childs = childs(action: :update)
  end

  def reorder_childs
    authorize! :update, @geo_ref
    priorities = params.require(:priorities)

    childs(action: :update).each do |c|
      next unless priorities.key? c.id.to_s

      c.update!(priority: priorities[c.id.to_s])
    end

    render json: {}
  end

  def sort_routes
    authorize! :update, @geo_ref
    @routes = routes(action: :update)
  end

  def reorder_routes
    authorize! :update, @geo_ref
    priorities = params.require(:priorities)

    routes(action: :update).each do |r|
      next unless priorities.key? r.id.to_s

      r.update!(priority: priorities[r.id.to_s])
    end

    render json: {}
  end

  def new
    @geo_ref = GeoRef.new(params.permit(:type))

    if params.key? :parent_id
      parent = GeoRef.find(params[:parent_id])
      @geo_ref.parent = parent
      @geo_ref.access = parent.access
    end

    authorize! :create, @geo_ref
    render :new
  end

  def edit
    authorize! :update, @geo_ref
  end

  def create
    @geo_ref = GeoRef.new(geo_ref_params)
    authorize! :create, @geo_ref
    
    @geo_ref.copy_parent_effective_permissions if @geo_ref.parent.present?

    respond_to do |format|
      if @geo_ref.save
        format.html { redirect_to geo_ref_path(@geo_ref), notice: _('Geo ref was successfully created.') }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize! :update, @geo_ref
    respond_to do |format|
      if @geo_ref.update(geo_ref_params)
        format.html { redirect_to geo_ref_path(@geo_ref), notice: _('Geo ref was successfully updated.') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize! :destroy, @geo_ref
    @geo_ref.destroy
    respond_to do |format|
      redirect_url = if @geo_ref.parent.present?
                       geo_ref_path(@geo_ref.parent)
                     else
                       geo_refs_path
                     end
      format.html { redirect_to redirect_url, notice: _('Geo ref was successfully destroyed.') }
    end
  end

  def select_items
    authorize! :read, @geo_ref
  end

  def move_items
    authorize! :read, @geo_ref

    new_geo_ref = @move_items_params.new_geo_ref
    @move_items_params.selected_routes.each do |route|
      route.geo_ref = new_geo_ref
      route.skip_geo_ref_update_stats = true
    end
    @move_items_params.selected_geo_refs.each do |geo_ref|
      geo_ref.parent = new_geo_ref
      geo_ref.skip_parent_changed_validation = true
    end

    if @move_items_params.valid?
      authorize! :read, new_geo_ref

      @move_items_params.selected_routes.each do |route|
        authorize! :create, route
        route.save!
      end
      @move_items_params.selected_geo_refs.each do |geo_ref|
        authorize! :create, geo_ref
        geo_ref.save!
      end

      new_geo_ref.update_self_and_parents_stats
      @geo_ref.update_self_and_parents_stats

      new_geo_ref.rebuild_effective_permissions \
        if @move_items_params.selected_geo_refs.any?
    
      redirect_to geo_ref_path(@geo_ref), notice: _('Child items have been moved to new location.')
    else
      select_items
      render :select_items
    end
  end

  private

  def routes(action: :read, order: [:priority, :name])
    @geo_ref.routes.accessible_by(current_ability, action).order(order)
  end

  def childs(action: :read, order: [:priority, :name])
    @geo_ref.childs.accessible_by(current_ability, action).order(order)
  end

  def set_geo_ref
    @geo_ref_for_paper_trail = @geo_ref = GeoRef.find(params[:id])
  end

  def geo_ref_type
    params.require(:geo_ref).permit(:type)
  end

  def geo_ref_params
    p = params.require(:geo_ref).permit(
      :name,
      :type,
      :parent_id,
      :description,
      :body,
      :lat,
      :lng,
      :zone_id,
      :height,
      :orientation,
      :access,
      tag_ids: [],
      alternative_names: []
    )
    p[:alternative_names]&.reject!(&:blank?)
    p
  end

  def geo_ref_move_items_params
    params.fetch(:geo_refs_controller_move_items_params, {}).permit(
      :new_geo_ref_id,
      route_ids: [],
      geo_ref_ids: []
    )
  end

  def set_move_items_params
    @move_items_params = GeoRefsController::MoveItemsParams.new
    @move_items_params.new_geo_ref = GeoRef.find(
      geo_ref_move_items_params[:new_geo_ref_id]
    ) unless geo_ref_move_items_params[:new_geo_ref_id].blank?

    @move_items_params.routes = routes(action: :destroy)
    @move_items_params.selected_routes = routes(action: :destroy) \
      .where(id: geo_ref_move_items_params[:route_ids].to_a.reject(&:blank?))

    @move_items_params.geo_refs = childs(action: :destroy)
    @move_items_params.selected_geo_refs = childs(action: :destroy) \
      .where(id: geo_ref_move_items_params[:geo_ref_ids].to_a.reject(&:blank?))
  end
end

app/views/geo_refs/_access_level_badge.html.erb
<%- if geo_ref.access == 'private' -%>
  <span class="badge badge-danger" data-toggle="tooltip" title="<%= _('Location is private') %> ">
    <i class="fa fa-user-circle"></i>
  </span>
<%- elsif geo_ref.access == 'confidential' -%>
  <span class="badge badge-danger" data-toggle="tooltip" title="<%= _('Location is confidential') %> ">
    <i class="fa fa-user-secret"></i>
  </span>
<%- end -%>

app/views/geo_refs/_dropdown.html.erb
<%-
  dropdown_link_options = {
    class: 'dropdown-item',
    icon_class: ['fw']
  }
-%>
<% if can?(:update, geo_ref) -%>
  <%= icon_link_to 'edit', _('Edit location'), edit_geo_ref_path(geo_ref), **dropdown_link_options %>
  <%= icon_link_to 'edit', _('Edit child items'), select_items_geo_ref_path(geo_ref), **dropdown_link_options %>
  <div class="dropdown-divider"></div>
<% end -%>
<% if can?(:create, Comment.new(target: geo_ref, user: current_user)) -%>
  <%= icon_link_to Comment, _('Add comment'), new_geo_ref_comment_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if can?(:create, GeoRef.new(parent: geo_ref)) -%>
  <%- [
      Country,
      Region,
      Crag,
      Sector,
      Parking
    ].each do |type| -%>
    <%- if type.valid_parent_class?(geo_ref.class) -%>
      <%- label = case
                  when type == Country then _('Add country')
                  when type == Region  then _('Add region')
                  when type == Crag    then _('Add crag')
                  when type == Sector  then _('Add sector')
                  when type == Parking then _('Add parking')
                  end
      -%>
      <%= icon_link_to(
        type,
        label,
        new_geo_refs_path(type: type.to_s, parent_id: geo_ref.id),
        **dropdown_link_options
      ) %>
    <%- end -%>
  <%- end -%>
<%- end -%>
<% if geo_ref.is_a?(Crag) && can?(:create, Route.new(geo_ref: geo_ref)) -%>
  <%= icon_link_to Route, _('Add route'), new_geo_ref_route_path(geo_ref), **dropdown_link_options %>
<%- end -%>
<% if can?(:create, Photo.new(target: geo_ref, user: current_user)) -%>
  <%= icon_link_to Photo, _('Add photo'), new_geo_ref_photo_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if can?(:create, Topo.new(target: geo_ref)) -%>
  <%= icon_link_to Topo, _('Add topo'), new_geo_ref_topo_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if SecondaryZone.valid_geo_ref_type?(geo_ref.class) && can?(:create, SecondaryZone.new(geo_ref: geo_ref)) -%>
  <%= icon_link_to SecondaryZone, _('Add climbing zone'), new_geo_ref_secondary_zone_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if Closure.valid_geo_ref_type?(geo_ref.class) && can?(:create, Closure.new(geo_ref: geo_ref)) -%>
  <%= icon_link_to Closure, _('Add closure'), new_with_template_geo_ref_closures_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if Regulation.valid_geo_ref_type?(geo_ref.class) && can?(:create, Regulation.new(geo_ref: geo_ref)) -%>
  <%= icon_link_to Regulation, _('Add climbing regulation'), new_geo_ref_regulation_path(geo_ref), **dropdown_link_options %>
<% end -%>
<% if geo_ref.is_a?(Parking) && can?(:create, Path.new(geo_ref: geo_ref)) -%>
  <%= icon_link_to Path, _('Add path'), new_geo_ref_path_path(geo_ref), **dropdown_link_options %>
<% end -%>

app/views/geo_refs/_form.html.erb
<%= simple_form_for(@geo_ref.becomes(GeoRef)) do |form| %>
  <%= back_button %>
  <%= form.error_notification %>

  <h3 class="page-header"><%= _('General Information') %></h3>
  <%= form.input(
    :name,
    label: _('Name')
  ) %>
  <%= form.input(
    :alternative_names,
    label: _('Alternative names'),
    placeholder: _('Add more names...'),
    hint: _('To add alternative names enter a name and press ENTER or click [add]'),
    as: :tags,
  ) %>
  <%= form.input(:type, as: :hidden) %>
  <%= form.input(
    :access,
    label: _('Access'),
    as: :access_level,
    hint: _('Access levels control the visibility of this location.')
  ) %>
  <%= form.input(:parent_id, as: :hidden) %>
  <%= form.input(
    :description,
    label: _('Summary'),
    placeholder: _('Short description of the location...')
  ) %>
  <%= form.input(
    :body,
    as: :text,
    label: _('Description'),
    placeholder: _('Long description, facts, history...')
  ) %>

  <h3 class="page-header"><%= _('Additional Information') %></h3>
  <%- if @geo_ref.supports_zone? %>
    <%= form.association :zone, label: _('Climbing zone'), include_blank: true %>
  <%- end -%>
  <%- if @geo_ref.supports_height? %>
    <%= form.input(
      :height,
      label: _('Height'),
      placeholder: _('in meters')
    ) %>
  <%- end -%>
  <%- if @geo_ref.supports_orientation? %>
    <%= form.input(
      :orientation,
      label: _('Orientation'),
      placeholder: _('in degree (360 north, 90 east, 180 south, 270 west)')
    ) %>
  <%- end -%>
  <%= form.input(
    :lat,
    label: _('Coordinates'),
    as: :geolocation
  ) %>

  <%= render partial: 'taggables/form', locals: { form: form, target: @geo_ref } %>

  <%= form.button :submit %>
<% end %>

app/views/geo_refs/_head.html.erb
<%= render partial: 'photos/cover_photo', locals: { photo: geo_ref.photos.cover_photos.first } %>

<%- content_for :dropdown do -%>
  <%= render partial: 'geo_refs/dropdown', locals: { geo_ref: geo_ref } %>
<% end -%>

<%- content_for :breadcrumb do -%>
  <%= render partial: 'geo_refs/parent_breadcrumb_nav', :locals => { :geo_ref => geo_ref } %>
<%- end -%>

<%- content_for :title_right do -%>
  <% if geo_ref.orientation.present? -%>
    <div class="compass"><div class="compass-pointer" style="transform: rotate(<%= geo_ref.orientation %>deg)"></div></div>
  <% end -%>
  <% if geo_ref.height.present? -%>
    <div class="messure_height"><%= geo_ref.height %>m</div>
  <% end -%>
<% end -%>

<%- content_for :title do -%>
  <%= geo_ref.name %>
  <small><%= _(geo_ref.class.name) %></small>
  <%= render partial: 'geo_refs/access_level_badge', :locals => { :geo_ref => geo_ref } %>
  <%= render partial: 'geo_refs/routes_grade_stats', :locals => { :geo_ref => geo_ref } %>
<%- end -%>

<%- content_for :icon, geo_ref.icon -%>

app/views/geo_refs/_parent_breadcrumb_nav.html.erb
<% include_self ||= false %>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="<%= browse_geo_refs_path %>"><span class="fa fa-globe"></span></a></li>
    <% geo_ref.parents.reverse.each do |parent| -%>
      <li class="breadcrumb-item"><%= link_to parent.name, geo_ref_path(parent) %></li>
    <% end -%>
    <% if include_self -%>
      <li class="breadcrumb-item"><%= link_to geo_ref.name, geo_ref_path(geo_ref) %></li>
    <% end -%>
  </ol>
</nav>

app/views/geo_refs/_path.html.erb
<%-
  include_self ||= false
  path = geo_ref.parents.reverse
  path << geo_ref if include_self
-%>
<% path.each do |parent| -%>
  <%= link_to parent.name, geo_ref_path(parent) %> /
<% end -%>

app/views/geo_refs/_primary_tab_nav.html.erb
<%- content_for :tab_nav do -%>
  <%= render_navigation do |primary|
    primary.item :search, _('Search'), geo_refs_path
    primary.item :browse, _('Browse'), browse_geo_refs_path, highlights_on: %r(/geo_refs/(?:\d+|browse)$)
    primary.dom_class = 'nav nav-tabs mb-3'
  end %>
<%- end -%>

app/views/geo_refs/edit.html.erb
<%- content_for :buttons do -%>
  <% if can?(:destroy, @geo_ref) -%>
    <%= link_to "<span class=\"fa fa-trash\"></span> #{_('Delete')}".html_safe, geo_ref_path(@geo_ref), method: :delete, data: { confirm: _('Are you sure?') }, class: 'btn btn-danger pull-right' %>
  <% end %>
<% end %>

<%- content_for :title, _('Editing %{geo_ref_type}') % { geo_ref_type: _(@geo_ref.type) } -%>
<%- content_for :icon, @geo_ref.icon -%>

<%= render 'form' %>

app/views/geo_refs/index.html.erb
<%- content_for :title, _('Locations') -%>
<%- content_for :icon, GeoRef.icon -%>

<%= render partial: 'geo_refs/primary_tab_nav' %>

<%= search_form_for @q do |f| %>
  <div class="form-group">
    <%= f.label _('Type') %>
    <%= f.select :type_eq,
      GeoRef.geo_ref_types.map { |t| [t, t] },
      { include_blank: true },
      { :class => 'form form-control form-group' } %>
  </div>
  <div class="form-group">
    <%= f.label _('Search') %>
    <div class="input-group">
      <%= f.search_field :search_full_text, class: 'form-control', placeholder: _('Search terms...') %>
      <div class="input-group-append">
        <%= f.submit :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

<ul class="content-list">
  <% @geo_refs.each do |geo_ref| -%>
    <%= render partial: 'geo_refs/content-list/default', :locals => { :item => geo_ref } %>
  <% end -%>
</ul>

<%= paginate @geo_refs %>

app/views/geo_refs/new.html.erb
<%- content_for :title, _('New %{geo_ref_type}') % { geo_ref_type: _(@geo_ref.type) } -%>
<%- content_for :icon, @geo_ref.icon -%>

<%= render 'form' %>

app/views/geo_refs/show.html.erb
<%= render partial: 'geo_refs/head', :locals => { :geo_ref => @geo_ref } %>
<%= render partial: 'geo_refs/secondary_tab_nav', :locals => { :geo_ref => @geo_ref } %>

<% @closures.each do |closure| -%>
  <%= render partial: 'closures/alert', locals: { closure: closure } %>
<% end -%>
<% if @route_closures.any? -%>
  <%= render partial: 'closures/alert_routes_with_closures' %>
<% end -%>

<%= render(
  partial: 'zones/icon',
  locals: {
    item: @geo_ref.zone,
    size: '3x'
  }
) if @geo_ref.zone.present? %>
<% @geo_ref.secondary_zones.each do |sr| -%>
  <% if can?(:update, sr) -%>
    <%= render(
      partial: 'zones/icon',
      locals: {
        item: sr.zone,
      }
    ) %>
    <%= sr.description %>
    <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_geo_ref_secondary_zone_path(@geo_ref, sr), class: 'btn btn-link btn-sm' %>
  <% end %>
<% end -%>

<%- if @geo_ref.alternative_names.any? -%>
  <%= _('Other names') %>: <%= @geo_ref.alternative_names.join(', ') %>
<%- end -%>

<%= render partial: 'location_map', :locals => { :geo_ref => @geo_ref } %>

<p><em><%= @geo_ref.description %></em></p>

<%= render partial: 'taggables/tags_by_category', :locals => { :tags => @geo_ref.tags } %>

<% if @geo_ref.body.present? -%>
  <%= markdown @geo_ref.body %>

  <hr></hr>
<% end -%>

<% if @childs.present? %>
  <ul class="content-list">
    <li>
      <div class="header"><%= _('Regions') %></div>
      <% if can? :update, @geo_ref -%>
        <a class="btn btn-sm btn-outline-secondary pull-right" href="<%=  sort_childs_geo_ref_path @geo_ref %>">
          <i class="fa fa-arrows-v" aria-hidden="true"></i> <%= _('change order') %>
        </a>
      <% end -%>
    </li>
    <% @childs.each do |c| %>
      <%= render partial: 'geo_refs/content-list/default', :locals => { :item => c } %>
    <% end %>
  </ul>
<% end %>

<% if @routes.present? %>
  <ul class="content-list">
    <li>
      <div class="header"><%= _('Routes') %></div>
      <% if can? :update, @geo_ref -%>
        <a class="btn btn-sm btn-outline-secondary pull-right ml-1" href="<%=  sort_routes_geo_ref_path @geo_ref %>">
          <i class="fa fa-arrows-v" aria-hidden="true"></i> <%= _('change order') %>
        </a>
      <% end -%>
    </li>
    <% @routes.each do |r| %>
      <%= render(
        partial: 'routes/content-list/default',
        locals: {
          item: r,
          show_closures: true
        }
      ) %>
    <% end %>
  </ul>
<% end %>

<% if @topos.present? %>
  <ul class="content-list">
    <li><div class="header"><%= _('Topos') %></div></li>
    <% @topos.each do |topo| %>
      <%= render partial: 'topos/content-list/default', :locals => { :item => topo } %>
    <% end %>
  </ul>
<% end %>

app/views/geo_refs/sort_routes.html.erb
<%= render partial: 'geo_refs/head', :locals => { :geo_ref => @geo_ref } %>
<%= render partial: 'geo_refs/secondary_tab_nav', :locals => { :geo_ref => @geo_ref } %>

<h3><%= _('Editing route order') %></h3>

<p><%= _('Drag routes below to sort them') %>:</p>

<sortable-list
  :initial-list="<%= @routes.to_json only: %i[id name] %>"
  reorder-url="<%= reorder_routes_geo_ref_path(@geo_ref) %>"
  ></sortable-list>