config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  authenticate :user, lambda { |u| u.role == 'admin' } do
      mount Sidekiq::Web => '/sidekiq'
  end
  devise_for :users

  get '403', to: 'errors#forbidden', as: 'forbidden'
  get '404', to: 'errors#not_found', as: 'not_found'
  get '422', to: 'errors#unprocessable_entity'
  get '500', to: 'errors#internal_server_error'

  root to: "geo_refs#index"

  get 'profile', to: 'profile#show'
  patch 'profile', to: 'profile#update'
  get 'profile/password', to: 'profile#password'
  patch 'profile/password', to: 'profile#update_password'

  resources :search, only: %i[index]
  resources :photos, only: %i[index show edit update destroy]
  resources :topos
  resources :zones, only: %i[index]
  resources :regulations, only: %i[index show edit update destroy] do
    resources :regulated_geo_refs, only: %i[new create]
  end
  resources :regulated_geo_refs, only: %i[edit update destroy]
  resources :inventories, only: [:show]
  resources :routes, only: %i[index show edit update destroy] do
    collection do
      get 'autocomplete'
    end
    resources :ascents, only: [:index, :new]
    resources :ticklists, only: [:index, :new]
    resources :photos, only: %i[index new create]
    resources :comments, only: %i[index new create]
    resources :inventories do
      member do
        put 'remove'
      end
    end
    resources :route_links, only: %i[new create edit update destroy]
    resources :versions, only: [:index]
  end
  resources :route_links, only: %i[show]

  resources :closures, only: %i[index show edit update destroy] do
    member do
      get :add_geo_ref_form
      post :add_geo_ref
      post :remove_geo_ref
      get :add_route_form
      post :add_route
      post :remove_route
    end
    collection do
      get :feed
    end
    resources :season_closures, only: %i[new create]
  end
  resources :season_closures, only: %i[edit update destroy]

  resources :ascents, only: %i[index show]
  resources :ticklists, only: %i[index show]

  resources :users, only: %i[show index] do
    resources :ascents, except: :show
    resources :ticklists, except: :show
    resources :photos, only: [:index]
    resources :versions, only: [:index]
  end

  resources :first_ascent_people do
    resources :versions, only: [:index]
    collection do
      get 'autocomplete'
    end
  end
  get 'scales/:scope', to: 'scales#table', defaults: { scope: 'climbing' }

  resources :geo_refs, except: :new  do
    collection do
      get(
        'new/:type',
        to: 'geo_refs#new',
        constraints: { type: /(Country|Region|Crag|Sector|Parking)/ },
        as: 'new'
      )
      get 'browse'
      get 'autocomplete'
      get 'map'
    end

    member do
      get 'map_items'
      get :sort_routes
      put :reorder_routes
      get :sort_childs
      put :reorder_childs
      get :select_items
      patch :move_items
    end

    resources :routes, only: %i[new create index] do
      collection do
        get :autocomplete
      end
    end
    resources :ascents, only: [:index]
    resources :ticklists, only: [:index]
    resources :approaches, only: [:index]
    resources :photos, only: %i[index new create]
    resources :topos
    resources :secondary_zones, only: %i[new create edit update destroy]
    resources :comments, only: %i[index new create]
    resources :paths, only: %i[index new create]
    resources :permissions, only: %i[index create edit update destroy]
    resources :regulations, only: %i[index new create]
    resources :closures, only: %i[index new create] do
      collection do
        get :new_with_template
        get :feed
      end
    end
    resources :versions, only: [:index]
  end

  resources :grades, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :styles, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :comments, only: %i[index edit update destroy]

  resources :paths, only: %i[index show edit update destroy] do
    member do
      post 'add_geo_ref'
      post 'remove_geo_ref'
      get 'map_items'
    end
  end

  resources :products, only: [] do
    collection do
      get 'autocomplete'
    end
  end

  resources :versions, only: [:index]

  get 'help', to: redirect('/help/README.html'), as: nil
  get 'help/*path', to: 'help#show', as: 'help'
  
  namespace :admin do
    root to: 'dashboard#dashboard'
    get '/monitoring', to: 'monitoring#index'
    get '/sys_info', to: 'sys_info#index'
    get '/background_jobs', to: 'background_jobs#index'
    resources :users do
      collection do
        get :members
        get :contributors
        get :admins
        get 'autocomplete'
      end
    end

    resources :vendors do
      collection do
        get 'autocomplete'
      end
    end
    resources :products do
      collection do
        get 'autocomplete'
      end
    end
  end

  get 'custom_layout', format: :css, to: 'custom_layout#index', as: :custom_layout

  get 'password_strength', to: 'password_strength#check'

  get '/abilities/:id', to: 'abilities#show'

  namespace :api do
    namespace :embed do
      namespace :v1 do
        resources :geo_refs, only: [] do
          collection do
            get :with_closures
          end
          resources :closures, only: %i[index] do
            collection do
              get :feed
            end
          end
        end
        resources :closures, only: %i[index] do
          collection do
            get :feed
          end
        end
      end
    end
  end

  health_check_routes
end

app/models/route_link.rb
class RouteLink < ApplicationRecord
  class << self
    KIND_DESCRIPTIONS = {
      N_('belay') => N_('Shares a common belay with another route'),
      N_('start_with') => N_('Uses the start of another route'),
      N_('end_with') => N_('Uses the end of another route'),
      N_('overlap') => N_('Overlaps with another route'),
      N_('cross') => N_('Crosses another route'),
    }.freeze

    KINDS = KIND_DESCRIPTIONS.keys.freeze 

    def kind_descriptions
      KIND_DESCRIPTIONS
    end

    def kinds
      KINDS
    end

    def valid_kind?(kind)
      KINDS.include? kind
    end

    def icon
        'random'
    end
  end

  belongs_to :route_from, class_name: 'Route', foreign_key: 'route_from_id'
  belongs_to :route_to, class_name: 'Route', foreign_key: 'route_to_id'

  validates :kind, presence: true
  validate :validate_kind
  def validate_kind
    return if kind.blank?
    return if self.class.valid_kind? kind

    errors.add(:kind, _('is not a valid kind'))
  end

  validates :anchor_number, numericality: { only_integer: true, allow_nil: true }
  validates :first_anchor_number, numericality: { only_integer: true, allow_nil: true }
  validates :last_anchor_number, numericality: { only_integer: true, allow_nil: true }

  validate :validate_routes
  def validate_routes
    return unless route_to.present? && route_from.present?

    errors.add(:route_to, _('must be on the same crag')) unless route_from.geo_ref_id == route_to.geo_ref_id
  end

  def supports_first_anchor_number?
    %w[end_with cross overlap].include? kind
  end

  def supports_last_anchor_number?
    %w[start_with overlap].include? kind
  end

  validates(
    :first_anchor_number,
    absence: true,
    unless: :supports_first_anchor_number?
  )
  validates(
    :last_anchor_number,
    absence: true,
    unless: :supports_last_anchor_number?
  )

  def inventories
    query = \
    case kind
    when 'belay'
      route_to.inventories.where(role: 'belay')
    when 'cross'
      route_to.inventories.where(
        role: 'intermediate anchor',
        anchor_number: first_anchor_number
      ) if first_anchor_number.present?
    when 'start_with'
      route_to.inventories.where(
        'anchor_number <= ?', last_anchor_number
      ) if last_anchor_number.present?
    when 'end_with'
      route_to.inventories.where(
        'anchor_number >= ?', first_anchor_number
      ) if first_anchor_number.present?
    when 'overlap'
      route_to.inventories.where(
        'anchor_number >= ? AND anchor_number <= ?',
        first_anchor_number,
        last_anchor_number
      ) if first_anchor_number.present? && last_anchor_number.present?
    end

    return Inventory.none if query.nil?

    query
  end

  has_paper_trail(
    meta: {
      route_id: :route_from_id,
      geo_ref_id: proc { |l| l.route_from.geo_ref_id }
    }
  )
end

app/controllers/route_links_controller.rb
class RouteLinksController < ApplicationController
  before_action :set_route_link, only: %i[edit update destroy show]
  before_action :set_route
  helper_method :kind_present?

  def new
    @route_link = RouteLink.new(
      route_from: @route,
      kind: params.dig(:route_link, :kind)
    )
    authorize! :create, @route_link
  end

  def edit
    authorize! :update, @route_link
  end

  def create
    @route_link = RouteLink.new(route_link_params)
    @route_link.route_from = @route
    authorize! :create, @route_link

    if @route_link.save
      redirect_to route_path(@route), notice: _('RouteLink was successfully created.')
    else
      render :new
    end
  end

  def update
    authorize! :update, @route_link

    if @route_link.update(route_link_params)
      redirect_to route_path(@route), notice: _('RouteLink was successfully updated.')
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @route_link
    @route_link.destroy
    redirect_to route_path(@route), notice: _('RouteLink was successfully removed.')
  end

  def show
    authorize! :read, @route_link
    redirect_to route_path(@route_link.route_from)
  end

  private

  def set_route_link
    @route_link = RouteLink.find(params[:id])
  end

  def set_route
    @route = Route.find(params[:route_id])
    authorize! :read, @route
  end

  def kind_present?
    params.dig(:route_link, :kind).present?
  end

  def route_link_params
    params \
      .require(:route_link) \
      .permit(
        :route_to_id,
        :description,
        :kind,
        :anchor_number,
        :first_anchor_number,
        :last_anchor_number
      )
  end
end

app/views/route_links/_form.html.erb
<%= simple_form_for([@route, @route_link]) do |form| -%>
  <%= back_button %>
  <%= form.error_notification %>

  <%= form.input(
    :route_from,
    label: _('Route'),
    as: :string,
    disabled: true,
    input_html: { value: @route_link.route_from.name }
  ) %>
  <%= form.input(
    :anchor_number,
    label: _('Bolt number'),
    hint: _('Number of the first bolt in this route.')
  ) %>

  <%= form.input(
    :kind,
    as: :hidden
  ) %>
  <%= form.input(
    :description,
    label: _('Description'),
    hint: _('Additional remarks regarding the route.'),
  ) %>

  <h3><%= _('Target Route') %></h3>

  <%= form.input(
    :route_to,
    label: _('Route'),
    as: :autocomplete,
    autocomplete_url: autocomplete_geo_ref_routes_path(@route.geo_ref),
  ) %>
  <%= form.input(
    :first_anchor_number,
    label: _('First used bolt'),
    hint: _('The number of the first bolt used.')
  ) if @route_link.supports_first_anchor_number? %>
  <%= form.input(
    :last_anchor_number,
    label: _('Last used bolt'),
    hint: _('The number of the last bolt used.')
  ) if @route_link.supports_last_anchor_number? %>

  <%= form.button :submit %>
<% end -%>

app/views/route_links/_kind_form.html.erb
<%= simple_form_for([@route, @route_link], url: new_route_route_link_path(@route), method: :get) do |form| -%>
  <%= form.error_notification %>

  <%= form.input(
    :kind,
    label: _('Type'),
    hint: _('Type of relation between the routes.'),
    as: :select,
    collection: RouteLink.kind_descriptions.map { |k,desc| [_(desc),k] },
    include_blank: false,
  ) %>

  <%= form.button :submit, _('Continue') %>
<% end -%>

app/views/route_links/_route_from.html.erb
<%= icon_for route_link %>
<%- path_helper ||= :route_path -%>
<%- route_name = link_to route_link.route_from.name, send(path_helper, route_link.route_from) -%>
<%- case route_link.kind -%>
<%- when 'belay' -%>
  <%= _('The route %{route_name} uses the same belay.').html_safe % { route_name: route_name } %>
<%- when 'start_with' -%>
  <%= _('The route %{route_name} has the same start.').html_safe % { route_name: route_name } %>
<%- when 'end_with' -%>
  <%= _('The route %{route_name} has the same end.').html_safe % { route_name: route_name } %>
<%- when 'cross' -%>
  <%= _('The route %{route_name} crosses this route.').html_safe % { route_name: route_name } %>
<%- when 'overlap' -%>
  <%= _('The route %{route_name} overlaps with this route.').html_safe % { route_name: route_name } %>
<%- end -%>
<%- if can? :update, route_link -%>
  <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_route_route_link_path(route_link.route_from, route_link), class: 'btn btn-link btn-sm' %>
<%- end -%>
<br>

app/views/route_links/_route_to.html.erb
<%= icon_for route_link %>
<%- path_helper ||= :route_path -%>
<%- route_name = link_to route_link.route_to.name, send(path_helper, route_link.route_to) -%>
<%- case route_link.kind -%>
<%- when 'belay' -%>
  <%= _('Uses the belay of %{route_name}.').html_safe % { route_name: route_name } %>
<%- when 'start_with' -%>
  <%= _('Starts with the route %{route_name}.').html_safe % { route_name: route_name } %>
<%- when 'end_with' -%>
  <%= _('Ends with the route %{route_name}.').html_safe % { route_name: route_name } %>
<%- when 'cross' -%>
  <%= _('Crosses the route %{route_name}.').html_safe % { route_name: route_name } %>
<%- when 'overlap' -%>
  <%= _('Overlaps with the route %{route_name}.').html_safe % { route_name: route_name } %>
<%- end -%>
<%- if can? :update, route_link -%>
  <%= link_to '<span class="fa fa-pencil"></span>'.html_safe, edit_route_route_link_path(route_link.route_from, route_link), class: 'btn btn-link btn-sm' %>
<%- end -%>
</br>

app/views/route_links/edit.html.erb
<% content_for :title, _('Editing route link') %>
<% content_for :icon, @route_link.icon %>

<% content_for :buttons do %>
  <% if can?(:destroy, @route_link) -%>
    <%= link_to "<span class=\"fa fa-trash\"></span> #{_('Delete')}".html_safe, route_route_link_path(@route_link.route_from, @route_link), method: :delete, data: { confirm: _('Are you sure?') }, class: 'btn btn-danger pull-right' %>
  <% end %>
<% end %>

<%= render 'form' %>

app/views/route_links/new.html.erb
<% content_for :title, _('New route link') %>
<% content_for :icon, @route_link.icon %>

<%- if kind_present? -%>
  <%= render 'form' %>
<%- else -%>
  <%= render 'kind_form' %>
<%- end -%>